# Generated by Django 3.1.7 on 2021-04-05 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itemstore', '0004_auto_20210405_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
